name: 自动push防止Actions自动停止

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,15 * *'
  repository_dispatch:
    types: start_action

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || !github.event.sender.id

    steps:
      - uses: actions/checkout@v3

      - name: Adding git info
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Creating an empty commit
        run: |
          git commit --allow-empty -m "Auto amazing commit"

      - name: Pushing
        run: |
          git push origin HEAD:main
