name: 自动push防止Actions自动停止

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 1,15 * *'
    repository_dispatch:
        types: start_action

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id

        steps:
            - name: Getting the repo
              uses: actions/checkout@v3

            - name: Re setting the url for `origin`
              run: |
                  git remote set-url origin https://${{ github.repository_owner }}:${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git
            - name: Adding git info
              run: |
                  git config --global user.name "nima789"
                  git config --global user.email "nima789@gmail.com"
            - name: Creating an empty commit
              run: |
                  git commit --allow-empty -m "Auto amazing commit"

            - name: Finilly pushing the repo
              run: |
                  git push origin main
